import "fake-indexeddb/auto";
import test from "node:test";
import assert from "node:assert/strict";
import { JSDOM } from "jsdom";
import { setTimeout as delay } from "node:timers/promises";
import { saveActiveCount, loadActiveCount } from "../src/count-store.js";
import { lockCoordinator } from "../src/coordinator-ui.js";
test("public counting defaults stay unconfirmed, MAX persists and invalid input stays incomplete", async (t) => {
  const dom = new JSDOM('<div id="app"></div><div id="toast"></div>', { url: "https://example.test/lush-inventory/", pretendToBeVisual: true });
  globalThis.window = dom.window; globalThis.document = dom.window.document;
  Object.defineProperty(globalThis, "navigator", { configurable: true, value: dom.window.navigator });
  globalThis.CSS = { escape: (value) => value };
  globalThis.alert = () => {};
  await saveActiveCount({ schemaVersion: 2, id: "ui", fileName: "zero.xlsx", products: [{ id: "p", plu: "01", category: "A", description: "Item", onHand: 5, display: "0", cupboard: "0", storeRoom: "0", confirmed: false, provenance: "untouched" }] });
  await import("../src/app.js?ui-test");
  t.after(() => { lockCoordinator(); dom.window.close(); });
  assert.ok(document.querySelector("#coordinator"));
  document.querySelector("#continueCount").click();
  assert.equal(document.querySelector('[data-field="display"]').value, "0");
  assert.ok(document.querySelector(".product").textContent.includes("Not started"));
  document.querySelector("[data-max]").click();
  await delay(30);
  assert.equal((await loadActiveCount()).products[0].display, "5");
  assert.ok(document.querySelector(".product").textContent.includes("Accepted from pre-inventory"));
  const field = document.querySelector('[data-field="display"]');
  field.value = "2x"; field.dispatchEvent(new window.Event("input", { bubbles: true }));
  await delay(30);
  assert.equal((await loadActiveCount()).products[0].display, "2x");
  assert.equal(document.querySelector("[data-status]").textContent, "Check value");
  field.value = "<img src=x>"; field.dispatchEvent(new window.Event("input", { bubbles: true }));
  await delay(30);
  document.querySelector("#review").click();
  assert.equal(document.querySelectorAll(".reviewRow img").length, 0);
  assert.ok(document.querySelector(".reviewRow").textContent.includes("<img src=x>"));
});
