import "fake-indexeddb/auto";
import test from "node:test";
import assert from "node:assert/strict";
import { JSDOM } from "jsdom";
import { setTimeout as delay } from "node:timers/promises";
import { mountCoordinator, lockCoordinator } from "../src/coordinator-ui.js";
import { lockVault } from "../src/coordinator-store.js";
const OWNER_PIN = process.env.LUSH_TEST_PIN;
if (!OWNER_PIN) throw new Error("Set LUSH_TEST_PIN to the configured owner PIN before running vault tests.");
const waitFor = async (predicate) => { for (let i = 0; i < 100; i++) { if (predicate()) return; await delay(10); } throw new Error("UI did not reach expected state"); };
test("coordinator unlocks, archives, records OOD and removes private markup on lock", async (t) => {
  const dom = new JSDOM('<div id="app"></div>', { url: "https://example.test/lush-inventory/", pretendToBeVisual: true });
  globalThis.window = dom.window; globalThis.document = dom.window.document;
  globalThis.FormData = dom.window.FormData;
  t.after(() => { lockCoordinator(); dom.window.close(); });
  const root = document.getElementById("app");
  const count = { schemaVersion: 2, id: "ui-count", fileName: "ui.xlsx", importedAt: "2026-10-01T10:00:00Z", postingDate: "2026-10-01", products: [{ id: "p", plu: "1", department: "HAIR", unit: "PCS", category: "A", description: "Item", cost: 2, onHand: 3, display: "2", cupboard: "0", storeRoom: "0", confirmed: true, provenance: "physical-recount" }] };
  count.products.push({ ...count.products[0], id: "q", plu: "2", description: "Related item", onHand: 1 });
  count.products.push({ ...count.products[0], id: "ambiguous", plu: "1", department: "GIFTS", unit: "KG", description: "Different identity" });
  mountCoordinator(root, { getActiveCount: () => count, saveActiveCount: async () => {}, onExit: () => {}, toast: () => {} });
  assert.ok(root.textContent.includes("Unlock"));
  root.querySelector('[name="pin"]').value = "9999";
  root.querySelector("form").dispatchEvent(new window.Event("submit", { bubbles: true, cancelable: true }));
  await waitFor(() => root.querySelector("#pinError")?.textContent.includes("Incorrect"));
  root.querySelector('[name="pin"]').value = OWNER_PIN;
  root.querySelector("form").dispatchEvent(new window.Event("submit", { bubbles: true, cancelable: true }));
  await waitFor(() => root.querySelector("#archiveCurrent"));
  root.querySelector("#archiveCurrent").click();
  await waitFor(() => root.querySelector("#allHistory"));
  root.querySelector('[data-outcome="p"]').click();
  const outcome = root.querySelector("#outcomeForm");
  outcome.elements.declaredQuantity.value = "3";
  outcome.elements.reason.value = "tester-pending";
  outcome.elements.note.value = "Private follow-up";
  outcome.elements.resolved.checked = true;
  outcome.dispatchEvent(new window.Event("submit", { bubbles: true, cancelable: true }));
  await waitFor(() => root.querySelector("#outcomeForm")?.elements.note.value === "Private follow-up" && !root.querySelector("#outcomeForm").elements.resolved.checked);
  const link = root.querySelector("#linkForm");
  link.elements.target.value = "0"; link.elements.note.value = "Suspected wrong punch";
  link.dispatchEvent(new window.Event("submit", { bubbles: true, cancelable: true }));
  await waitFor(() => root.querySelector("#linkForm")?.parentElement.querySelector("p.small")?.textContent.includes("Suspected wrong punch"));
  root.querySelector('[data-tab="ood"]').click();
  root.querySelector("#newBatch").click();
  const form = root.querySelector("#batchForm");
  form.elements.plu.value = "1"; form.elements.plu.dispatchEvent(new window.Event("change", { bubbles: true }));
  assert.equal(form.elements.department.value, "");
  assert.equal(form.elements.unit.value, "");
  assert.match(root.querySelector("#productIdentityWarning").textContent, /choose|conflict|multiple/i);
  for (const [key, value] of Object.entries({ plu: "1", description: "Private batch <script>", department: "HAIR", productionDate: "2026-03-01", quantity: "2", unit: "PCS" })) form.elements.namedItem(key).value = value;
  form.dispatchEvent(new window.Event("submit", { bubbles: true, cancelable: true }));
  await waitFor(() => root.textContent.includes("Private batch <script>"));
  assert.equal(root.querySelectorAll("script").length, 0);
  root.querySelector("#recordCheck").click();
  const check = root.querySelector("#checkForm");
  check.elements.department.value = "OTHER SECTION";
  check.dispatchEvent(new window.Event("submit", { bubbles: true, cancelable: true }));
  await waitFor(() => root.textContent.includes("OTHER SECTION"));
  root.querySelector('[data-tab="ood"]').click();
  assert.ok(root.querySelector("#oodCheckDate"));
  root.querySelector("#oodCheckDate").value = "2026-10-02";
  root.querySelector("#oodCheckDate").dispatchEvent(new window.Event("change", { bubbles: true }));
  assert.ok(root.textContent.includes("Overdue"));
  Object.defineProperty(document, "hidden", { configurable: true, value: true });
  document.dispatchEvent(new window.Event("visibilitychange"));
  assert.ok(!root.textContent.includes("Private batch"));
  assert.ok(root.querySelector('[name="pin"]'));
  dom.window.close();
});
test("a failed operation that locks the vault removes private markup and shows its error", async (t) => {
  const dom = new JSDOM('<div id="app"></div>', { url: "https://example.test/lush-inventory/", pretendToBeVisual: true });
  globalThis.window = dom.window; globalThis.document = dom.window.document; globalThis.FormData = dom.window.FormData;
  t.after(() => { lockCoordinator(); dom.window.close(); });
  const root = document.getElementById("app");
  const count = { schemaVersion: 2, id: "failed-operation", fileName: "Private archive", postingDate: "2026-10-01", products: [{ id: "p", plu: "1", category: "A", description: "Item", onHand: 2, display: "2", cupboard: "0", storeRoom: "0", confirmed: true, provenance: "physical-recount" }] };
  mountCoordinator(root, { getActiveCount: () => count, saveActiveCount: async () => { lockVault(); throw new Error("Storage failed after locking"); }, onExit: () => {}, toast: () => {} });
  root.querySelector('[name="pin"]').value = OWNER_PIN;
  root.querySelector("form").dispatchEvent(new window.Event("submit", { bubbles: true, cancelable: true }));
  await waitFor(() => root.querySelector("#archiveCurrent"));
  root.querySelector("#archiveCurrent").click();
  await waitFor(() => root.querySelector("#pinError")?.textContent.includes("Storage failed"));
  assert.ok(!root.textContent.includes("Private archive"));
});
